### PR TITLE
Add params hash to session

### PR DESCRIPTION
**Pull request by bhtabor**
Add simple params hash to session. You can add params anywhere flow and state are used. The params hash will then be available on the `current_session.params`.

For example: `step_to flow: :some_flow, state: :some_state, params: { some_key: 'some_value' }`

### CODE REVIEW

**Comment by mgomes** [comment]
Thanks so much for the PR, @bhtabor! 🎈 

This is a pretty extensive PR. I have quite a few changes for Stealth 2.0 that are going to land soon that rewrite some parts of sessions.

Aside from that, though, can you tell me a little about the need for params? Do your bot(s) use a database?

**Comment by bhtabor** [comment]
Thank you @mgomes You are right, we don't use a database.

A sample use case would be a restaurant ordering conversation which sends a final request after collecting inputs from multiple states.

Let's say it starts by asking for the restaurant id, then it checks the restaurant and steps to asking the user to choose a menu. But when it steps to this state, say get_menu, something like a param could be used to pass restaurant_id to the get_menu state without a need for a datatabase.

This PR is a non breaking change and JSON dumps to Redis string and JSON loads from Redis string ('flow->state?{some_key: 'some_value'}) only when params exists. It would have been better to save a hash on Redis with flow, state, and params as keys, but that would be a breaking change.

Please let me know if you need more information.

**Comment by mgomes** [comment]
Closing this. Really appreciate the thoughtful PR, but I think rather than adding a redis store to Stealth, this would be better served as a separate gem. ❤️

**Comment by bhtabor** [comment]
Hi @mgomes, thanks for reviewing. I agree we should avoid extra dependency. I'm open to moving this to a plugin. Isn't Redis already a dependency though?

> Closing this. Really appreciate the thoughtful PR, but I think rather than adding a redis store to Stealth, this would be better served as a separate gem. ❤️

**Pull request closed without merging**
