### PR TITLE
Fix replies spec

### PR DESCRIPTION
**Pull request by sunny**
Fixes broken specs introduced in #284… sorry about that 🙄

### CODE REVIEW

**Comment by sunny** [comment]
Unrelated to this issue, but note that I didn’t manage to run the specs properly on my side. I am getting some multibyte character errors.

```sh
sunny@httpster ~/c/stealth> bundle exec rspec spec/version_spec.rb

An error occurred while loading ./spec/version_spec.rb.
Failure/Error: EXCLUDED_CHARS_RE = /#{EXCLUDED_CHARS_ESC.join('|')}/

ArgumentError:
  invalid multibyte character
# ./lib/stealth/core_ext/string.rb:7:in `<class:String>'
# ./lib/stealth/core_ext/string.rb:3:in `<top (required)>'
# ./lib/stealth/core_ext.rb:4:in `require'
# ./lib/stealth/core_ext.rb:4:in `block in <top (required)>'
# ./lib/stealth/core_ext.rb:3:in `each'
# ./lib/stealth/core_ext.rb:3:in `<top (required)>'
# ./lib/stealth/base.rb:19:in `require'
# ./lib/stealth/base.rb:19:in `<top (required)>'
# ./lib/stealth.rb:1:in `require'
# ./lib/stealth.rb:1:in `<top (required)>'
# ./spec/spec_helper.rb:8:in `require'
# ./spec/spec_helper.rb:8:in `<top (required)>'
# ./spec/version_spec.rb:3:in `require'
# ./spec/version_spec.rb:3:in `<top (required)>'
No examples found.


Finished in 0.00005 seconds (files took 1.26 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

```sh
sunny@httpster ~/c/stealth> ruby -v
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-darwin19]
sunny@httpster ~/c/stealth> uname -a
Darwin httpster 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

Changing

```rb
EXCLUDED_CHARS = %w[" ' . , ! ? ( ) - _ ` ‘ ’ “ ”].freeze
```

to

```rb
EXCLUDED_CHARS = %w[" ' . , ! ? ( ) - _ `].freeze
```

fixes the issue for me and specs run smoothly (except for the specs where these character exclusions are tested).

**Comment by mgomes** [comment]
Thanks for the followup PR.

With respect the `EXCLUDED_CHARS` I'll need to look more closely. I'd like to keep those smart quotes if possible since they are pretty common on auto complete from phones and such.

Curious though, do you have a bot in production already or you developing one? I just ask because for version 2.0 of this gem, this project is going to be re-named to Xip Kit and so I have a new repo going. https://github.com/xipkit/xip. Could you migrate over to that? It's exactly the same as the 2.0 Beta 2 of Stealth other than the name change.

**Comment by sunny** [comment]
For `EXCLUDED_CHARS`, let me know if you’d like me to try anything out. Maybe an issue on my machine only so it’s maybe not worth it to pursue this here if development is moving to xip.

I’m working with @emorissettegregoire who has several bots already and depends on `stealth-messagebird`, so migrating from Stealth to Xip might take some time. Is there any migration guide to help us switch?

**Comment by mgomes** [comment]
Hey @sunny, can you try adding a magic comment to the top of `core_ext/string.rb` and see if it fixes it? You can add this right below the `frozen_string` comment:

```ruby
# encoding: utf-8
```

As for the migration from Stealth -> Xip, I'll for sure provide a guide. If you're using the current stealth 2.0 beta all it will be is a find/replace("Stealth", "Xip"). Same for your custom gem. I am not introducing any breaking API changes. Actually I hope to never do that!

Let me know if I can help you make the migration in any way. Always happy to help!

**Comment by sunny** [comment]
The magic comment did not seem to change anything, still getting `invalid multibyte character` errors 🤷🏻

**Comment by mgomes** [comment]
@sunny Hmm, I am not sure. Try using a proper array with double-quoted elements, maybe even single-quoted elements. 

Sorry I can't be of more help, I can't reproduce the issue on any of my machines. Happy to merge in any fix that helps you, though.

**Comment by mgomes** [comment]
Interesting, which version of Ruby was giving you trouble?

**Comment by sunny** [comment]
That one:
> ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-darwin19]

**Comment by sunny** [comment]
Hey @mgomes, I think this branch can be merged regardless of the encoding issue I have with specs. That way specs won’t stay broken on the main branch.

**Comment by mgomes** [comment]
Closing due to staleness. Feel free to re-open though if this is still causing issues!

**Pull request closed without merging**
